In [1]:
import numpy as np
print(np.__version__)

1.13.3


In [5]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [7]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arryay=arr[arr % 2 ==1]
print(arryay)

[1 3 5 7 9]


In [8]:
arr[arr % 2 ==1]=-1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
clear

In [11]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr=np.arange(10)
arr.reshape(2,-2)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

In [18]:
arr=np.vstack([a,b])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
arr=np.hstack([a,b])

In [20]:
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
a=np.array([1 ,2, 3])

In [23]:
a

array([1, 2, 3])

In [24]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])